"""
Attack path Neo4j ingest helpers.

Bridges the machine-readable ``attack_paths.json`` contract to Cypher and
optional direct Neo4j writes.
"""

from __future__ import annotations

from collections.abc import Mapping, Sequence
from typing import Any

from src.core.knowledge.driver import get_db
from src.core.knowledge.models import EDGE_TYPES, NODE_TYPES
from src.core.knowledge.schema import GraphSchema


_IDENTITY_KEY_BY_NODE_TYPE: dict[str, str] = {
    "Target": "id",
    "Endpoint": "url",
    "Parameter": "id",
    "Finding": "id",
    "Task": "id",
    "Decision": "id",
    "ToolRun": "id",
    "AttackPath": "id",
}


def build_attack_path_cypher(payload: Mapping[str, Any]) -> str:
    """Build a standalone Cypher script from an ``attack_paths.json`` payload."""
    nodes, edges, metadata = _normalise_payload(payload)
    node_lookup = {str(node["node_id"]): node for node in nodes}

    lines = [
        "// Generated by SHIGOKU attack path ingest",
        f"// session_id: {metadata.get('session_id', 'unknown')}",
        "",
    ]

    for node in nodes:
        lines.append(_build_node_cypher(node))
        lines.append("")

    for edge in edges:
        lines.append(_build_edge_cypher(edge, node_lookup))
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def ingest_attack_path_payload(
    payload: Mapping[str, Any],
    *,
    driver: Any | None = None,
    apply_constraints: bool = True,
) -> dict[str, Any]:
    """Write an ``attack_paths.json`` payload into Neo4j."""
    nodes, edges, metadata = _normalise_payload(payload)
    node_lookup = {str(node["node_id"]): node for node in nodes}

    active_driver = driver or get_db()
    if apply_constraints:
        GraphSchema.apply_constraints(driver=active_driver)

    with active_driver.session() as session:
        for node in nodes:
            query, params = _build_node_query(node)
            session.run(query, **params)

        for edge in edges:
            query, params = _build_edge_query(edge, node_lookup)
            session.run(query, **params)

    return {
        "status": "ok",
        "session_id": metadata.get("session_id"),
        "nodes_written": len(nodes),
        "edges_written": len(edges),
        "node_types": sorted({str(node["node_type"]) for node in nodes}),
        "edge_types": sorted({str(edge["edge_type"]) for edge in edges}),
    }


def _normalise_payload(
    payload: Mapping[str, Any],
) -> tuple[list[dict[str, Any]], list[dict[str, Any]], dict[str, Any]]:
    if not isinstance(payload, Mapping):
        raise ValueError("attack path payload must be a mapping")

    raw_nodes = payload.get("nodes", [])
    raw_edges = payload.get("edges", [])
    raw_metadata = payload.get("metadata", {})

    if not isinstance(raw_nodes, Sequence) or isinstance(raw_nodes, (str, bytes)):
        raise ValueError("payload.nodes must be a list")
    if not isinstance(raw_edges, Sequence) or isinstance(raw_edges, (str, bytes)):
        raise ValueError("payload.edges must be a list")
    if not isinstance(raw_metadata, Mapping):
        raise ValueError("payload.metadata must be a mapping")

    nodes = [_normalise_node(node) for node in raw_nodes]
    edges = [_normalise_edge(edge) for edge in raw_edges]
    metadata = dict(raw_metadata)

    node_ids = {str(node["node_id"]) for node in nodes}
    for edge in edges:
        if str(edge["source_node_id"]) not in node_ids:
            raise ValueError(
                f"edge source node not found: {edge['source_node_id']}"
            )
        if str(edge["target_node_id"]) not in node_ids:
            raise ValueError(
                f"edge target node not found: {edge['target_node_id']}"
            )

    return nodes, edges, metadata


def _normalise_node(raw: Any) -> dict[str, Any]:
    if not isinstance(raw, Mapping):
        raise ValueError("each node must be a mapping")

    node_type = str(raw.get("node_type") or "")
    if node_type not in NODE_TYPES:
        raise ValueError(f"unsupported node_type: {node_type}")

    node = dict(raw)
    node["node_id"] = str(node.get("node_id") or "")
    node["display_label"] = str(node.get("display_label") or node["node_id"])
    node["node_type"] = node_type
    node["evidence_state"] = str(node.get("evidence_state") or "")
    node["source_refs"] = _normalise_string_list(node.get("source_refs"))
    node["extra"] = dict(node.get("extra") or {})
    if not node["node_id"]:
        raise ValueError("node_id is required")
    return node


def _normalise_edge(raw: Any) -> dict[str, Any]:
    if not isinstance(raw, Mapping):
        raise ValueError("each edge must be a mapping")

    edge_type = str(raw.get("edge_type") or "")
    if edge_type not in EDGE_TYPES:
        raise ValueError(f"unsupported edge_type: {edge_type}")

    edge = dict(raw)
    edge["edge_id"] = str(edge.get("edge_id") or "")
    edge["source_node_id"] = str(edge.get("source_node_id") or "")
    edge["target_node_id"] = str(edge.get("target_node_id") or "")
    edge["edge_type"] = edge_type
    edge["source_refs"] = _normalise_string_list(edge.get("source_refs"))
    edge["extra"] = dict(edge.get("extra") or {})
    if not edge["edge_id"]:
        raise ValueError("edge_id is required")
    return edge


def _normalise_string_list(value: Any) -> list[str]:
    if not isinstance(value, Sequence) or isinstance(value, (str, bytes)):
        return []
    return [str(item) for item in value if item is not None]


def _node_identity(node: Mapping[str, Any]) -> tuple[str, Any]:
    node_type = str(node["node_type"])
    key = _IDENTITY_KEY_BY_NODE_TYPE[node_type]
    if key == "url":
        extra = node.get("extra")
        if isinstance(extra, Mapping):
            url = extra.get("url")
            if url:
                return key, str(url)
        return key, str(node.get("display_label") or node["node_id"])
    return key, str(node["node_id"])


def _build_node_properties(node: Mapping[str, Any]) -> dict[str, Any]:
    props = {
        "id": str(node["node_id"]),
        "node_type": str(node["node_type"]),
        "display_label": str(node.get("display_label") or ""),
        "evidence_state": str(node.get("evidence_state") or ""),
        "why_in_path": str(node.get("why_in_path") or ""),
        "source_refs": _normalise_string_list(node.get("source_refs")),
        "blocked_reason": str(node.get("blocked_reason") or ""),
        "next_validation_hint": str(node.get("next_validation_hint") or ""),
        "observed_at": node.get("observed_at"),
        "inferred_after": node.get("inferred_after"),
    }

    extra = node.get("extra")
    if isinstance(extra, Mapping):
        for key, value in extra.items():
            if key in props:
                continue
            props[str(key)] = value

    return props


def _build_edge_properties(edge: Mapping[str, Any]) -> dict[str, Any]:
    props = {
        "id": str(edge["edge_id"]),
        "edge_type": str(edge["edge_type"]),
        "display_label": str(edge.get("display_label") or ""),
        "evidence_state": str(edge.get("evidence_state") or ""),
        "why_in_path": str(edge.get("why_in_path") or ""),
        "source_refs": _normalise_string_list(edge.get("source_refs")),
    }

    extra = edge.get("extra")
    if isinstance(extra, Mapping):
        for key, value in extra.items():
            if key in props:
                continue
            props[str(key)] = value

    return props


def _build_node_query(node: Mapping[str, Any]) -> tuple[str, dict[str, Any]]:
    label = str(node["node_type"])
    identity_key, identity_value = _node_identity(node)
    properties = _build_node_properties(node)
    query = (
        f"MERGE (n:{label} {{{identity_key}: $identity_value}})\n"
        "SET n += $properties"
    )
    return query, {
        "identity_value": identity_value,
        "properties": properties,
    }


def _build_edge_query(
    edge: Mapping[str, Any],
    node_lookup: Mapping[str, Mapping[str, Any]],
) -> tuple[str, dict[str, Any]]:
    source_node = node_lookup[str(edge["source_node_id"])]
    target_node = node_lookup[str(edge["target_node_id"])]
    source_label = str(source_node["node_type"])
    target_label = str(target_node["node_type"])
    source_key, source_value = _node_identity(source_node)
    target_key, target_value = _node_identity(target_node)
    rel_type = str(edge["edge_type"])
    properties = _build_edge_properties(edge)

    query = (
        f"MATCH (src:{source_label} {{{source_key}: $src_identity_value}})\n"
        f"MATCH (dst:{target_label} {{{target_key}: $dst_identity_value}})\n"
        f"MERGE (src)-[r:{rel_type} {{id: $edge_id}}]->(dst)\n"
        "SET r += $properties"
    )
    return query, {
        "src_identity_value": source_value,
        "dst_identity_value": target_value,
        "edge_id": str(edge["edge_id"]),
        "properties": properties,
    }


def _build_node_cypher(node: Mapping[str, Any]) -> str:
    label = str(node["node_type"])
    identity_key, identity_value = _node_identity(node)
    properties = _build_node_properties(node)
    return (
        f"MERGE (n:{label} {{{identity_key}: {_to_cypher_literal(identity_value)}}})\n"
        f"SET n += {_to_cypher_literal(properties)}"
    )


def _build_edge_cypher(
    edge: Mapping[str, Any],
    node_lookup: Mapping[str, Mapping[str, Any]],
) -> str:
    source_node = node_lookup[str(edge["source_node_id"])]
    target_node = node_lookup[str(edge["target_node_id"])]
    source_label = str(source_node["node_type"])
    target_label = str(target_node["node_type"])
    source_key, source_value = _node_identity(source_node)
    target_key, target_value = _node_identity(target_node)
    rel_type = str(edge["edge_type"])
    properties = _build_edge_properties(edge)

    return (
        f"MATCH (src:{source_label} {{{source_key}: {_to_cypher_literal(source_value)}}})\n"
        f"MATCH (dst:{target_label} {{{target_key}: {_to_cypher_literal(target_value)}}})\n"
        f"MERGE (src)-[r:{rel_type} {{id: {_to_cypher_literal(str(edge['edge_id']))}}}]->(dst)\n"
        f"SET r += {_to_cypher_literal(properties)}"
    )


def _to_cypher_literal(value: Any) -> str:
    if value is None:
        return "null"
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)) and not isinstance(value, bool):
        return repr(value)
    if isinstance(value, str):
        escaped = (
            value.replace("\\", "\\\\")
            .replace("'", "\\'")
            .replace("\n", "\\n")
        )
        return f"'{escaped}'"
    if isinstance(value, Sequence) and not isinstance(value, (str, bytes)):
        return "[" + ", ".join(_to_cypher_literal(item) for item in value) + "]"
    if isinstance(value, Mapping):
        parts = [
            f"{str(key)}: {_to_cypher_literal(item)}"
            for key, item in value.items()
        ]
        return "{" + ", ".join(parts) + "}"
    return _to_cypher_literal(str(value))
