from enum import Enum


class ObservationReason(str, Enum):
    SKIP_DISABLED = "SKIP_DISABLED"
    SKIP_NO_LLM_CLIENT = "SKIP_NO_LLM_CLIENT"
    SKIP_NOT_SUCCESS = "SKIP_NOT_SUCCESS"
    SKIP_NO_SIGNAL = "SKIP_NO_SIGNAL"
    SKIP_LOW_VALUE_TASK = "SKIP_LOW_VALUE_TASK"
    SKIP_BUDGET_EXCEEDED = "SKIP_BUDGET_EXCEEDED"
    SKIP_CIRCUIT_OPEN = "SKIP_CIRCUIT_OPEN"
    SKIP_TOKEN_BUDGET_EXCEEDED = "SKIP_TOKEN_BUDGET_EXCEEDED"
    SKIP_SAMPLING_POLICY = "SKIP_SAMPLING_POLICY"
    SKIP_QUEUE_OVERFLOW = "SKIP_QUEUE_OVERFLOW"
    ALLOW_HIGH_VALUE_SIGNAL = "ALLOW_HIGH_VALUE_SIGNAL"
    ALLOW_SAMPLED = "ALLOW_SAMPLED"
